module.exports =   {
    "LOAD_TODOS_SUCCESS" : 'LOAD_TODOS_SUCCESS',
    "ADD_TODOS" : 'ADD_TODOS',
    "REFRESHING_TODOS" : 'REFRESHING_TODOS',
    "TASK_TITLE_CHANGED" : 'TASK_TITLE_CHANGED',
    "EDIT_TODOS" : 'EDIT_TODOS',
    "DELETE_TODOS" : 'DELETE_TODOS',
    "CHANGE_TODO_TYPE":'CHANGE_TODO_TYPE'
};