/**
 * Created by Ramm on 2/9/2018.
 */
const EMAIL_CHANGED = Symbol('EMAIL_CHANGED');
const LOAD_QUESTIONS = Symbol('LOAD_QUESTIONS');
const LOAD_QUESTIONS_SUCCESS = Symbol('LOAD_QUESTIONS_SUCCESS');
const LOAD_QUESTIONS_ERROR = Symbol('LOAD_QUESTIONS_ERROR');
const ANSWER_CHANGED = Symbol('ANSWER_CHANGED');

module.exports = {
  LOAD_QUESTIONS,
  LOAD_QUESTIONS_SUCCESS,
  LOAD_QUESTIONS_ERROR,
  ANSWER_CHANGED,
  EMAIL_CHANGED,
};
